// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_w38Tp48HguyGW87IXlMOsIYiycTvtsQ',
    appId: '1:573422052827:web:90ccca92544ac92a3733fe',
    messagingSenderId: '573422052827',
    projectId: 'final-project-pbb-30e0a',
    authDomain: 'final-project-pbb-30e0a.firebaseapp.com',
    storageBucket: 'final-project-pbb-30e0a.firebasestorage.app',
    measurementId: 'G-LECRR779DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHGyuMhqSm81CcA-6by4CHAG8E_y8rSQ4',
    appId: '1:573422052827:android:80dd9e269743a3c63733fe',
    messagingSenderId: '573422052827',
    projectId: 'final-project-pbb-30e0a',
    storageBucket: 'final-project-pbb-30e0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF0PhmZCsBwjflh7nfEvUYM3C6UQCwlHc',
    appId: '1:573422052827:ios:7167323aa914c6093733fe',
    messagingSenderId: '573422052827',
    projectId: 'final-project-pbb-30e0a',
    storageBucket: 'final-project-pbb-30e0a.firebasestorage.app',
    iosBundleId: 'com.example.sdgEcoJump',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF0PhmZCsBwjflh7nfEvUYM3C6UQCwlHc',
    appId: '1:573422052827:ios:7167323aa914c6093733fe',
    messagingSenderId: '573422052827',
    projectId: 'final-project-pbb-30e0a',
    storageBucket: 'final-project-pbb-30e0a.firebasestorage.app',
    iosBundleId: 'com.example.sdgEcoJump',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_w38Tp48HguyGW87IXlMOsIYiycTvtsQ',
    appId: '1:573422052827:web:2f28273c6b6386853733fe',
    messagingSenderId: '573422052827',
    projectId: 'final-project-pbb-30e0a',
    authDomain: 'final-project-pbb-30e0a.firebaseapp.com',
    storageBucket: 'final-project-pbb-30e0a.firebasestorage.app',
    measurementId: 'G-SS134NED74',
  );
}
